services:
  nunvibe-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nunvibe-backend
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    restart: unless-stopped

  nunvibe-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nunvibe-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - nunvibe-backend
    restart: unless-stopped
